[package]
name = "jsontrek"
version = "0.1.7"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.95"
serde_json = "1.0"
serde_json_path = "0.7.1"
serde-wasm-bindgen = "0.6.5"
serde = "1.0"
log = "0.4.22"

[lib]
crate-type = ["cdylib", "rlib"]
