[package]
name = "jsontrek"
version = "0.1.1"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.73"
serde_json = "1.0"
serde_json_path = "0.7.1"
serde-wasm-bindgen = "0.6.5"

[lib]
crate-type = ["cdylib", "rlib"]
