version: '3'

tasks:
  build:
    cmds:
      - echo "Building..."
      - wasm-pack build --target bundler --out-name bundle --out-dir ./builds/bundle/pkg
      # - wasm-pack build --target web --out-name web --out-dir ./builds/web/pkg
      # - wasm-pack build --target nodejs --out-name node --out-dir ./builds/node/pkg
  build-all:
    cmds:
      - echo "Building..."
      - wasm-pack build --target bundler --out-name bundle --out-dir ./builds/bundle/pkg
      - wasm-pack build --target web --out-name web --out-dir ./builds/web/pkg
      - wasm-pack build --target nodejs --out-name node --out-dir ./builds/node/pkg
  test:
    cmds:
      - echo "Testing..."
  publish:
    dir: ./builds/node/pkg
    cmds:
      - echo "Publishing..."
      - npm publish