version: '3'

tasks:
  build:
    cmds:
      - echo "Building..."
      - wasm-pack build --target bundler --out-name bundle --out-dir ./builds/bundle/pkg

  build-node:
    cmds:
      - echo "Building..."
      - wasm-pack build --target nodejs --out-name node --out-dir ./builds/node/pkg


  build-all:
    cmds:
      - echo "Building..."
      - wasm-pack build --target bundler --out-name bundle --out-dir ./builds/bundle/pkg
      - wasm-pack build --target web --out-name web --out-dir ./builds/web/pkg
      - wasm-pack build --target nodejs --out-name node --out-dir ./builds/node/pkg
  echo-test:
    cmds:
      - echo "Testing..."
      - node ./benchmarks/jsontrek.mjs
  publish:
    dir: ./builds/bundle/pkg
    cmds:
      - echo "Publishing..."
      - npm publish
  patch:
    cmds:
      - echo "Patching..."
      - cargo bump patch
  tag:
    cmds:
      - echo "Tagging..."
      - git tag -a v${CARGO_PKG_VERSION} -m "v${CARGO_PKG_VERSION}"
  release:
    cmds:
      - echo "Releasing..."
      - task patch
      - task build
      - task publish